### ISSUE TITLE
Link to existing projects / articles

### ISSUE THREAD

**Issue by borkdude** [lread/clj-graal-docs#1]
Going to drop the raw links here. There might be important ones I'm forgetting. Please add to it.

CLIs:
- https://github.com/taylorwood/clojurl
- https://github.com/tomekw/cotd
- https://github.com/kkinnear/zprint/blob/master/doc/graalvm.md
- https://github.com/eraserhd/rep
- https://github.com/retrogradeorbit/bootleg
- https://github.com/borkdude/jet
- https://github.com/borkdude/babashka
- https://github.com/borkdude/clj-kondo

Tools / wrappers:
- https://github.com/taylorwood/clj.native-image

Articles:
- https://www.astrecipes.net/blog/2018/07/20/cmd-line-apps-with-clojure-and-graalvm/
- https://github.com/BrunoBonacci/graalvm-clojure
- https://blog.taylorwood.io/2018/05/02/graalvm-clojure.html
- https://www.innoq.com/en/blog/native-clojure-and-graalvm/
- https://nextjournal.com/kommen/clojure-berlin-prosemirror-transforms-with-graalvm-and-clojure (note: this is not necessarily about native binaries, but uses GraalVM with Truffle stuff)

Talks:
- https://www.youtube.com/watch?v=topKYJgv6qA

**Comment by sogaiu** [comment]
Here are some possible additions:

CLI
* https://github.com/borkdude/cljtree-graalvm
* https://github.com/kkinnear/zprint/blob/master/doc/graalvm.md
* https://github.com/stathissideris/optikon
* https://github.com/sogaiu/adorn
* https://gitlab.com/konrad.mrozek/cljfmt-graalvm/

Articles
* http://www.alysbrooks.com/using-graal-on-a-small-but-real-application.html
* http://insideclojure.org/2019/04/19/journal/#clojure-1101

Misc
* http://ssw.jku.at/Teaching/MasterTheses/Graal/TruffleClojure.pdf (Truffle)

**Comment by sogaiu** [comment]
Should I keep adding here if I find more?

https://github.com/latacora/wernicke

**Comment by borkdude** [comment]
@sogaiu If you want to add more, can you make a PR?

**Comment by sogaiu** [comment]
Ok, done: https://github.com/lread/clj-graal-docs/pull/12
