### ISSUE TITLE
Capture Graal RAM usage Slack chat in docs

### ISSUE THREAD

**Issue by lread** [lread/clj-graal-docs#18]
> Lee Read  4 days ago
Hello folks!  I am using native-image with the --no-server and -J-Xmx settings.  Do any of you know of any other settings or techniques that will reduce the amount of RAM that native-image requires to do its job?  My current use case is natively compiling an open source Clojure project's unit tests and running them. Because this is open source, I'd like to do this work on a free tier of a build service such as CircleCI or GitHub Actions.  My problem is that these free tiers have less RAM available than native-image requires, in this case, to do its work.
I am thinking that splitting the unit tests into multiple native-image runs could do the trick, but before I do that, I was wondering if anybody had some tips or tricks.

> Vojin Jovanovic  7 hours ago
We will be actively working on this in the future. Our goal is that projects should be able to build their tests on Travis. /cc @Codrut Stancu

> Codrut Stancu  4 hours ago
There are unfortunately no tricks. We're working on improving the resources consumption of the image building process, changes are expected to land in the 20.0 release

> Lee Read  2 minutes ago
Much thanks for your replies. And also much thanks for GraalVM!
Looking forward to changes ahead.

**Comment by borkdude** [comment]
Closing this just to clean up. Re-open if needed.
