### ISSUE TITLE
Patching script fails at line 97 because qualifier is not set

### ISSUE THREAD

**Issue by zilti** [lread/clj-graal-docs#24]
As the title says.

**Comment by lread** [comment]
Thanks @zilti will take a look!

**Comment by lread** [comment]
@zilti, to help us reproduce and fix your issue, can you please share the following:

1. what operating system and OS version are you using?
2. exactly how did you invoke `build-clojure-with-1472-patch.sh` (did you include any options?)

Thanks!

**Comment by zilti** [comment]
1. I'm using OpenSUSE Tumbleweed.
2. I ran `./build-clojure-with-1472-patch.sh -p CLJ-1472-reentrant-finally2.patch`, but the same happens when just running `./build-clojure-with-1472-patch.sh`.

**Comment by lread** [comment]
Thanks for following up @zilti, I have installed OpenSuse Tumbleweed and have not successfully reproduced your issue yet.  

The script checks for prerequisites, but not versions of those prerequisites.  We must be running different versions of things. My current guess is that on your system either maven is not extracting the clojure version correctly or bash is not parsing regexes as expected.  

Can you do me a favour? Please run the following a paste results to this issue.

```
mvn --version
bash --version
git --version
```

For my OpenSuse Tumbleweed install these return:
```
lee@localhost:~/proj/oss/clj-graal-docs/CLJ-1472/clojure> mvn --version
Apache Maven 3.6.2 (SUSE 3.6.2-1.1)
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.13-1-default", arch: "amd64", family: "unix"


lee@localhost:~/proj/oss/clj-graal-docs/CLJ-1472/clojure> bash --version
GNU bash, version 5.0.11(1)-release (x86_64-suse-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


lee@localhost:~/proj/oss/clj-graal-docs/CLJ-1472/clojure> git --version
git version 2.25.0
```

**Comment by zilti** [comment]
These are my values. I guess I at one point manually installed Maven, so my Maven version was completely outdated... I replaced it with the version from the repositories, and that works fine now. Thanks!

```
zilti@linux-xxfc:~> mvn --version
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T15:51:42+02:00)
Maven home: /home/zilti/applications/apache-maven
Java version: 1.8.0_242, vendor: IcedTea
Java home: /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.13-1-default", arch: "amd64", family: "unix"
zilti@linux-xxfc:~> bash --version
GNU bash, Version 5.0.11(1)-release (x86_64-suse-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder jünger <http://gnu.org/licenses/gpl.html>

Dies ist freie Software.  Sie darf verändert und verteilt werden.
Es wird keine Garantie gewährt, soweit das Gesetz es zulässt.
zilti@linux-xxfc:~> git --version
git version 2.25.0
```

**Comment by lread** [comment]
Great! Glad to hear all is resolved. Maybe I'll add a check for minimum maven version.
