### ISSUE TITLE
build script should allow selection of clojure commit

### ISSUE THREAD

**Issue by borkdude** [lread/clj-graal-docs#9]
https://github.com/lread/clj-graal-docs/blob/6324c22064918ab8d7b26824c5bf79f969c4741c/CLJ-1472/build-clojure-with-1472-patch.sh#L113

I think we want to use clojure 1.11.0-master here.

**Comment by lread** [comment]
After a good chat, we identified 2 primary uses:
1. the tool developer who wants to native compile their app, this person will use a 1.10.1 patched version of clojure
2. the clojure team dev who wants to make progress on CLJ-1472.  This person will likely work off HEAD of master but may want also to select different commits.

We decided to:
1. add a command line arg to specify which clojure commit/tag - defaulting to 1.10.1
2. include clojure git short sha in our generated version
3. use version from clojure pom.xml in our generated version (already doing this, I think)
4. make sure we are automatically selecting version of spec that selected commit of clojure uses
